import { cellText, collectColumns } from "./columns.js";
import { stripControlChars } from "./sanitize.js";

function esc(s: string): string {
  return stripControlChars(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Self-contained HTML report: embedded CSS (zebra rows, sticky header,
 * dark-mode aware), no external assets. Nested values render as compact
 * JSON in <code>. Safe to open from disk or paste into a page.
 */
export function renderHtml(rows: Record<string, unknown>[]): string {
  const cols = collectColumns(rows);
  const header = cols.map((c) => `<th>${esc(c)}</th>`).join("");
  const body = rows
    .map((row) => `<tr>${cols.map((c) => `<td>${esc(cellText(row[c]))}</td>`).join("")}</tr>`)
    .join("\n");
  const count = `${rows.length} row${rows.length === 1 ? "" : "s"}`;

  return `<!DOCTYPE html>
<!-- generated by dittosh -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>DQL results — ${count}</title>
<style>
  :root { color-scheme: light dark; }
  body { font-family: system-ui, -apple-system, "Segoe UI", sans-serif; margin: 2rem; }
  table { border-collapse: collapse; font-size: 0.875rem; }
  th, td { border: 1px solid CanvasText; padding: 0.35rem 0.7rem; text-align: left; vertical-align: top; }
  thead th { position: sticky; top: 0; background: Canvas; font-weight: 600; }
  tbody tr:nth-child(even) { background: color-mix(in srgb, CanvasText 6%, Canvas); }
  td { max-width: 40rem; overflow-wrap: anywhere; }
  footer { margin-top: 1rem; font-size: 0.8rem; opacity: 0.6; }
</style>
</head>
<body>
<table>
<thead><tr>${header}</tr></thead>
<tbody>
${body}
</tbody>
</table>
<footer>${count} · generated by dittosh</footer>
</body>
</html>`;
}
