/**
 * Stamp a release build with the obfuscated offline license token (spec M8).
 *
 *   npm run stamp:token          # tsx --env-file=.env scripts/stamp-token.ts
 *   npm run stamp:token -- --expires 2027-05-01   # override expiry detection
 *
 * Reads OFFLINE_TOKEN/DQL_OFFLINE_LICENSE + DATABASE_ID/DITTO_APP_ID from the
 * environment, verifies the token is not near expiry, then writes the
 * gitignored build/token-chunks.ts (7 XORed chunks + 5 decoys at fixed slots).
 * Follow with `RELEASE=true npm run build`.
 *
 * Never prints the token. Exit 1 on any failure.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { pack, STAMP_SLOTS, unpack } from "../src/identity/obfuscate.js";

/** Refuse to stamp a token expiring in fewer than this many days. */
export const MIN_EXPIRY_DAYS = 45;
/** Warn when stamping a token expiring in fewer than this many days. */
export const WARN_EXPIRY_DAYS = 90;

/**
 * Best-effort expiry extraction from a license token:
 *  - JWT: `exp` claim (seconds) in the payload
 *  - Ditto offline token: base64'd CBOR-ish map with an `expiry` ISO datetime
 * Returns an ISO date (YYYY-MM-DD) or null when undetectable.
 */
export function extractExpiry(token: string): string | null {
  const parts = token.split(".");
  const jwtPayload = parts.length === 3 ? parts[1] : undefined;
  if (jwtPayload) {
    try {
      const payload = JSON.parse(Buffer.from(jwtPayload, "base64url").toString("utf8")) as {
        exp?: unknown;
      };
      if (typeof payload.exp === "number") {
        return new Date(payload.exp * 1000).toISOString().slice(0, 10);
      }
    } catch {
      // not a JWT — fall through
    }
  }
  try {
    const decoded = Buffer.from(token, "base64").toString("utf8");
    const m = decoded.match(/expiry.{0,6}?(\d{4}-\d{2}-\d{2})T?/);
    const date = m?.[1];
    if (date) return date;
  } catch {
    // not base64 — fall through
  }
  return null;
}

export type ExpiryVerdict = "ok" | "warn";

/** Throws when the token is too close to expiry; returns "warn" inside the warn window. */
export function checkExpiryWindow(daysLeft: number): ExpiryVerdict {
  if (daysLeft < MIN_EXPIRY_DAYS) {
    throw new Error(
      daysLeft < 0
        ? `token expired ${-daysLeft} days ago — get a fresh offline token before stamping`
        : `token expires in ${daysLeft}d (< ${MIN_EXPIRY_DAYS}d) — get a fresh offline token before stamping`,
    );
  }
  return daysLeft < WARN_EXPIRY_DAYS ? "warn" : "ok";
}

export function renderStampModule(
  appId: string,
  expiresOn: string,
  stamp: {
    salt: string;
    chunks: string[];
  },
): string {
  return `// @generated by scripts/stamp-token.ts (${new Date().toISOString().slice(0, 10)}) — do not edit, do not commit (gitignored).
export const STAMPED = true;
export const APP_ID = ${JSON.stringify(appId)};
export const EXPIRES_ON = ${JSON.stringify(expiresOn)};
export const SALT = ${JSON.stringify(stamp.salt)};
export const CHUNKS: string[] = ${JSON.stringify(stamp.chunks, null, 2)};
`;
}

export function main(argv: string[], env: NodeJS.ProcessEnv): number {
  const expiresIdx = argv.indexOf("--expires");
  const expiresOverride = expiresIdx === -1 ? undefined : argv[expiresIdx + 1];

  const token = env.OFFLINE_TOKEN ?? env.DQL_OFFLINE_LICENSE;
  const appId = env.DATABASE_ID ?? env.DITTO_APP_ID;
  if (!token || !appId) {
    console.error(
      "stamp-token: set OFFLINE_TOKEN and DATABASE_ID (repo-root .env, or DQL_OFFLINE_LICENSE/DITTO_APP_ID)",
    );
    return 1;
  }

  const expiry = expiresOverride ?? extractExpiry(token);
  if (!expiry) {
    console.error("stamp-token: could not detect token expiry — pass --expires YYYY-MM-DD");
    return 1;
  }
  if (Number.isNaN(new Date(expiry).getTime())) {
    console.error(`stamp-token: unparseable expiry "${expiry}"`);
    return 1;
  }

  const daysLeft = Math.floor((new Date(expiry).getTime() - Date.now()) / 86_400_000);
  try {
    if (checkExpiryWindow(daysLeft) === "warn") {
      console.warn(
        `stamp-token: WARNING — token expires ${expiry} (${daysLeft}d < ${WARN_EXPIRY_DAYS}d); plan a token refresh soon`,
      );
    }
  } catch (err) {
    console.error(`stamp-token: ${(err as Error).message}`);
    return 1;
  }

  const stamp = pack(token);
  // Self-check: the bundle must reassemble the exact token we were given.
  if (unpack(stamp.chunks, stamp.salt) !== token) {
    console.error("stamp-token: internal round-trip check failed — not writing");
    return 1;
  }

  const outDir = resolve(import.meta.dirname ?? ".", "..", "build");
  mkdirSync(outDir, { recursive: true });
  const outPath = resolve(outDir, "token-chunks.ts");
  writeFileSync(outPath, renderStampModule(appId, expiry, stamp));

  console.log(
    `stamp-token: wrote build/token-chunks.ts — app ${appId}, expiry ${expiry} (${daysLeft}d), ${STAMP_SLOTS} chunks`,
  );
  console.log("next: RELEASE=true npm run build");
  return 0;
}

// Run only when invoked directly (unit tests import the pure helpers above).
const invokedAs = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : "";
if (import.meta.url === invokedAs) {
  process.exit(main(process.argv.slice(2), process.env));
}
